### ISSUE TITLE
web interface not exist via composer installation

### ISSUE THREAD

**Issue by MR-omid** [Marty-Macfly/yii2-taxonomy#8]
hi marty  
i install this package via composer, but interface and controller and ... not exists.

**Comment by marty-macfly** [comment]
Hello,

Web interface was not in version 1.0.0, (it was only in dev, you can change your composer.json and replace * by dev-master so you're using the last version of the code).

Or just wait few minutes for version 1.1.0 to be create on packagist so it will be available through composer, just do a composer update.

Regards,
Macfly
