### ISSUE TITLE
usage question

### ISSUE THREAD

**Issue by MR-omid** [Marty-Macfly/yii2-taxonomy#9]
how to get list of terms or properties (name,value) ?
$post->envs or $post->terms return entity_terms table only.
Excuse me, I think I'm confused on how to use.
Here's what I want : 
entity : bag
properties: color,size
color property example  (name=>value) [cover=>red,front=>green,strap=>blue]
size property example (name=>value) [withStrap=>10kg,withOutStrap=9.8kg]

attach color and size to bag entity, get list of attached properties for use on view.

thanks.

**Comment by marty-macfly** [comment]
So bag is your model on which you want to add property color which can have name cover => value red.

So you need to add property color to you model.

```php
class Bag extends \yii\db\ActiveRecord
{   
    public function behaviors()
    {   
        return [
                PropertyTermBehavior::className(),
            ],
        ];
    }

        # Define the get method of property 'env'
        public function getColors()
        {
            return $this->getPropertyTerms('color');
        }

        # Define the set method of property 'env'
        public function setColors($terms)
        {
            return $this->setPropertyTerms('color', $terms);
        }

        # Add term by name and value
        public function addColor($name, $value)
        {
            return $this->addPropertyTerm('color', $name, $value);
        }

        # Detach term by name and value
        public function delColor($name, $value)
        {
            return $this->delPropertyTerm('color', $name, $value);
        }

        # Has term by name and value
        public function hasColor($name, $value)
        {
            return $this->hasPropertyTerm('color', $name, $value);
        }

}
```

Now you can get set color property with what value you want :
```php 
    $mybag = Bag::findOne(['id'=>1]);
    $mybag->addColor('cover', 'red');
    $mybag->addColor('front', 'green');
    $mybag->addColor('strap', 'blue');
```
You can now do to see all attributes of color :

```php
 print_r($bag->colors)
```

You should duplicate that in your model for size also.

Is that clearer ?
